service: serverless-simple-crm-api

plugins:
  - serverless-dotenv-plugin
custom:
  dotenv:
    logging: false
    include:
      - LOG_LEVEL

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:provider.custom.config.${self:provider.stage}.region}
  stage: ${opt:stage, "dev"}
  profile: ${env:AWS_PROFILE}
  timeout: 30
  environment:
    NODE_ENV: ${opt:stage, "dev"}
    MYSQL_DATABASE: ${env:MYSQL_DATABASE}
    MYSQL_USER: ${env:MYSQL_USER}
    MYSQL_PASSWORD: ${env:MYSQL_PASSWORD}
    MYSQL_HOST: ${env:MYSQL_HOST}
  custom:
    prefix: ${self:provider.stage}-crm-api
    description: "Simple CRM Serverless API"
    config:
      dev:
        region: eu-west-1

package:
  individually: true
  exclude:
    - ./*

layers:
  APINodeModules:
    compatibleRuntimes:
      - nodejs
    path: layers/api
    package:
      include:
        - ./**
    name: ${self:provider.custom.prefix}-node_modules
    description: Layer including CRM API production node modules

functions:
  hello:
    handler: api/handler.hello
    description: function that says hello when POST to its API Gateway endpoint
