service: serverless-simple-crm-api

plugins:
  - serverless-dotenv-plugin
custom:
  dotenv:
    logging: false
    include:
      - LOG_LEVEL

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${opt:stage, "dev"}
  profile: ${env:AWS_PROFILE}
  timeout: 900
  environment:
    NODE_ENV: ${opt:stage, "dev"}
  custom:
    prefix: ${self:provider.stage}-user-api
    description: "Simple CRM Serverless API"
    config:
      dev:
        account: ${self:provider.account}
        region: ${self:provider.region}

package:
  individually: true

functions:
  hello:
    handler: handler.hello
